name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bhaskarprajapati
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 3. Build and Push the Lunchbox!
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-docker:latest
